[gradle]
compiler=emmylu
distribution=gradle-8.9-bin.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip
kotlinVersion=2.0.21
androidGradlePluginVersion=8.5.2

[versions]
agp = "8.5.2"
kotlin = "2.0.21"
coreKtx = "1.15.0"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.09.00"
navigationCompose = "2.8.5"
okhttp = "4.12.0"
room = "2.6.1"
datastrore = "1.1.1"
coroutines = "1.8.1"
hilt = "2.52"
material = "1.12.0"
junit = "4.13.2"
junitExt = "1.2.1"
espresso = "3.6.1"
